name: Mini Mime Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.ruby }} / ${{ matrix.os }}"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ruby:
          - "3.3"
          - "3.4"
          - "4.0"
          - "jruby-10.0"
          - "jruby-10.1"
          - "truffleruby-34.0"
        include:
          - ruby: "4.0"
            os: windows-2025

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Tests
        run: bundle exec rake test

  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
