name: Update MIME type DB

on:
  schedule:
    # 10am on the 1st every month https://crontab.guru/#0_10_1_*_*
    - cron: "0 10 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_db:
    runs-on: ubuntu-24.04
    name: "Update MIME type DB"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - name: Update mime-types-data
        run: bundle update mime-types-data
      - name: Update DB
        run: bundle exec rake rebuild_db
      - name: Test updated DB
        run: bundle exec rake test
      - name: Create PR
        run: bin/db_pull_request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
